### PR TITLE
Add Nextcloud support

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
No account found:
filek5qlzm

Choose between clouds:
filejhjlfx

Show existing (nextcloud) accounts:
files1impz

Add account dialog:
filejutufc

### CODE REVIEW

**Comment by ramschmaerchen** [comment]
First of all, thanks for the PR. We will merge after testing.

**Comment by tobiasKaminsky** [comment]
If you need some changes, please do not hesitate to ask for it :-)

**Comment by ramschmaerchen** [comment]
Thanks, good to know!

I, or a colleague, will test the following (hopefully) next week:
- [ ] Compiling
- [ ] Syncing
- [ ] Deleting
- [ ] What happens when multiple accounts (oc AND nc) are present (IMPORTANT!)

**Comment by jancborchardt** [comment]
Any update here @ramschmaerchen? :) We could do a call for testing through the @Nextcloud twitter. :)

**Comment by tobiasKaminsky** [comment]
@ramschmaerchen any updates on this?

**Comment by sdukhovni** [comment]
This PR is 3 months old, any ETA for when it'll get tested and merged? This is the one thing preventing me from being able to use this app...

**Comment by Gomez** [comment]
@ramschmaerchen any updates? Maybe consider moving repo and account to nextcloud?

**Comment by mokkin** [comment]
@ramschmaerchen Is there any further testing needed? I would appreciate having nextcloud support too.
If you don't have enough time atm we could follow @Gomez advice to move the repo to nextcloud itself directly.

**Comment by tobiasKaminsky** [comment]
If it is moved to nextcloud repo the app still needs devs to maintain it and the android devs from nextcloud (I am one of them) cannot support this at the moment.

**Pull request merged**
